language: python
python:
    #  - "2.6"
  - "2.7"
    #  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
   - "export DISPLAY=:99.0" #Emulating display for pyplot to work
   - "sh -e /etc/init.d/xvfb start"
   - sleep 3 # give xvfb some time to start
   - pip install pytest
   - pip install pytest-cov
   - pip install codecov
   - echo $TRAVIS_PYTHON_VERSION
   - if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then sudo apt-get update; sudo apt-get install python-logilab-common;sudo apt-get install python-numpy; fi
   - pip install -r requirements.txt
script:
  - export PYTHONPATH=$PWD:$PYTHONPATH
  - pytest --cov=./
  - codecov
# # command to run tests

