language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
   - pip install pytest
   - pip install pytest-cov
   - pip install python-coveralls 
   - echo $TRAVIS_PYTHON_VERSION
   - if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then sudo apt-get update; sudo apt-get install python-logilab-common;sudo apt-get install python-numpy; fi
script:
  - export PYTHONPATH=$PWD:$PYTHONPATH
  - pytest --cov=./
  - coveralls
# # command to run tests

