language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
   - pip install pytest
   - echo $TRAVIS_PYTHON_VERSION
   - if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then apt-get install python-logilab-common;fi
script:
  - export PYTHONPATH=$PWD:$PYTHONPATH
  - pytest
# # command to run tests

